### ISSUE TITLE
Godot Issue Drafts — Batch 1 & 2

### ISSUE THREAD

**Issue by follower** [follower/experiment-github-issue-drafts#1]
Issues to write-up:

- [ ] Escape strings used with JavaScript `eval()`.
- [ ] Add advisory re: `eval()` use in documentation.
- [ ] Example download file via HTML.
- [ ] `XA_MALLOC`(?) Thread Local Storage vs compiler version issue/workaround.
- [ ] Update `XA_MALLOC` version to better handle Thread Local Storage issue.
- [ ] `_QDBitmap` naming spec compliance issue.
- [ ] Incorrect `DynamicFont` initialization. (Now here: https://github.com/godotengine/godot/issues/40787)
- [ ] Error on DMG export when trashing temporary file.

Batch 2:

- [ ]  Poor Anchor/Margin/Container interactions [[draft notes](https://github.com/follower/experiment-github-issue-drafts/issues/1#issuecomment-625146078)]
- [ ] `DynamicFont` lacks kerning. [[draft notes]](https://github.com/follower/experiment-github-issue-drafts/issues/1#issuecomment-627042038)]
- [ ] `find_node()` `owner`-related non-obviousness. [[draft notes](https://github.com/follower/experiment-github-issue-drafts/issues/1#issuecomment-627059268)]

**Comment by follower** [comment]
###  Poor Anchor/Margin/Container interactions

* Children of containers "automatically" have their anchors (e.g. from (0,0,1,1) to (0,0,0,0)) & margins (e.g. from (0,0,0,0) to (0,0, 1024, 600)) changed in certain circumstances & these changes get made & saved (IMO) unnecessarily.

* Children of containers get `_edit_use_anchors_` added to their saved meta data because of a related commit.

Related commits:

 * "[Improve the anchors and margin workflow](https://github.com/godotengine/godot/commit/e875f05c3bb026ed96e59d1651237852b174d00c)"

     * Appears to remove `editors/2d/keep_margins_when_changing_anchors` preference. (The preference is [mentioned here](https://old.reddit.com/r/godot/comments/97xryb/i_honestly_give_up_trying_to_understand_margins/e4bx2hw/) as part of a reply to "[I honestly give up trying to understand margins, anchors, and centering content with controls.](https://old.reddit.com/r/godot/comments/97xryb/i_honestly_give_up_trying_to_understand_margins/)".)

     * Appears to causes anchor/margin values to be changed in children of containers by disabling anchor mode--instead of "disabling" the edit controls/warning that they will be ignored/keeping the anchors & only changing the margins or something.

     * Adds `_edit_use_anchors_` to saved scenes.

 * "[Add option to keep margins when changing anchors #3997](https://github.com/godotengine/godot/pull/3997/files)" (re: "[Add option to disable margin change when anchors change #3979](https://github.com/godotengine/godot/issues/3979)")

     * The commit that added `editors/2d/keep_margins_when_changing_anchors`.

 * [`editor/plugins/canvas_item_editor_plugin.cpp#L4022`](https://github.com/godotengine/godot/blame/58435b0c917fd93d4244ed672e7fadd076dae608/editor/plugins/canvas_item_editor_plugin.cpp#L4022)

     * Multiple references to `_edit_use_anchors_`.

**Comment by follower** [comment]
### `DynamicFont` lacks kerning.

(Managed to work out how to fix an earlier kerning issue that caused kerning functionality to be removed from code base. Still need to write up an issue but summary here: https://twitter.com/RancidBacon/status/1260479576385499137 :D )

Existing issues:

 * "[kerning pairs not available in DynamicFont #35730](https://github.com/godotengine/godot/issues/35730)"
 * "[Dynamic font kerning bug #30014](https://github.com/godotengine/godot/issues/30014) (Also see [this comment](https://github.com/godotengine/godot/issues/30014#issuecomment-510058106) re: two different types of kerning tables and various font tools like [this one](https://opentype.js.org/glyph-inspector.html).)

Resources:

 * "[FreeType Glyph Conventions / IV / Kerning](https://www.freetype.org/freetype2/docs/glyphs/glyphs-4.html)" ([mirror](https://web.archive.org/web/20200323170337/https://www.freetype.org/freetype2/docs/glyphs/glyphs-4.html)) -- A good overview of what's required to implement kerning with FreeType--was linked to in one of the issues above. 

 * An implementation for reading the GPOS `kern` tables rather than (or in addition to) the old style `kern` tables: https://github.com/nothings/stb/blob/f54acd4e13430c5122cab4ca657705c84aa61b08/stb_truetype.h#L2492

   Since Godot already includes some `stb` code, including functionality based on this `stb` code might be an option--although I'd still like to know *why* Freetype doesn't support GPOS kern at all. (I assume it's because most people just use HarfBuzz?)

**Comment by follower** [comment]
### `find_node()` `owner`-related non-obviousness.

Three related issues:

 * Default value of `owner` as `true` is non-obvious.

 * Documentation talks about "scene instantiation" but doesn't make it explicit that use of `.duplicate()` (and *any* scripted instantiation/creation at all?) is sufficient to cause the `owner` value to be `null`).

 * There is no feedback why the search fails:

    * It's not obvious in the (remote) node tree that nodes have no/different owners.

    * Nor in the pretty printed tree.

    * Nor does the inspector show the `owner` to even suggest such a property exists.

Related issues/links:

 * "[How to find an instanced scene by its name?](https://godotengine.org/qa/17524/how-to-find-an-instanced-scene-by-its-name)"

 * "[find_node() for instanced nodes is counterintuitive #6811](https://github.com/godotengine/godot/issues/6811)"

 * "[find_node broken? #6843](https://github.com/godotengine/godot/issues/6843)"

 * "[Document find_node()'s owner argument behavior #10595](https://github.com/godotengine/godot/issues/10595)"

 * "[Document find_node()'s owner argument behaviour #22674](https://github.com/godotengine/godot/pull/22674)"
